### ISSUE TITLE
Nullpointer exception on Android 11 devices

### ISSUE THREAD

**Issue by prasannarupan** [Wootric/WootricSDK-Android#111]
Running into two NPE on Android 11 devices in our app. This is impacting users from preventing any feedback, makes the SDK useless.

Attached screenshot of the crashes from firebase.

<img width="1268" alt="Screen Shot 2021-08-28 at 6 02 54 PM" src="https://user-images.githubusercontent.com/393847/131234892-ddbc5fa5-e89d-4087-a6e4-f97813d7af7f.png">

<img width="1257" alt="Screen Shot 2021-08-28 at 6 02 43 PM" src="https://user-images.githubusercontent.com/393847/131234894-173c2e68-17c6-4d84-a91a-511dd8b2869c.png">

SDK Version is : 2.13.0.

**Comment by diegoserranoa** [comment]
Hi @prasannarupan , could you upgrade to the latest version? Version 2.13.0 is really old now and we've pushed a couple of fix and changes since then.

Thanks!

**Comment by prasannarupan** [comment]
@diegoserranoa sure we can push to the latest version.

**Comment by prasannarupan** [comment]
hi @diegoserranoa : our app has your SDK version 2.21.0 in production right now and the crash is still happening on Android 11 devices. I'd like your team to look into this and get it addressed. can you give me a timeline for this fix
![Screen Shot 2022-04-22 at 10 05 55 AM](https://user-images.githubusercontent.com/393847/164761606-7261e8e3-38b0-4e7a-8e40-9e6d76781fce.png)
?

**Comment by Tviljan** [comment]
We got similar crash:

![image](https://github.com/Wootric/WootricSDK-Android/assets/2995353/fa01a6a7-10b1-4eff-ab65-41907a7fb18d)
