### ISSUE TITLE
Wootric.stop() NullPointerException crash

### ISSUE THREAD

**Issue by johnp-dialpad** [Wootric/WootricSDK-Android#126]
### Given 
`wootric.survey()` has been called and callback function `WootricSurveyCallback.onSurveyWillShow()` has *not* yet been called.

### When
`wootric.stop()` is called

### Then
The app will crash with a `NullPointerException` in `SurveyManager.onGetEndUserIdSuccess()` or `SurveyManager.onCreateEndUserSuccess()`

```kotlin
    @Override
    public void onGetEndUserIdSuccess(long endUserId) {
        currentEvent.getEndUser().setId(endUserId); // <-- currentEvent is null

        if(currentEvent.getEndUser().hasProperties() ||
                currentEvent.getEndUser().hasExternalId() ||
                currentEvent.getEndUser().hasPhoneNumber()) {
            sendUpdateEndUserRequest();
        }

        showSurvey();
    }
```

```kotlin
    @Override
    public void onCreateEndUserSuccess(long endUserId) {
        currentEvent.getEndUser().setId(endUserId); <-- currentEvent is null

        showSurvey();
    }
```

This can be avoided if you wait for callback function `WootricSurveyCallback.onSurveyWillShow()` but documentation doesn't explain this, and it would be nice to not have to do that.

**Comment by nordfalk** [comment]
I had some angry users because the survey started in some very inconvenient momens.
Therefore, to avoid the user inconveniences I called wootric.stop()

Now, because of this bug, I have NPE crashes all over the place instead  :angry: 

Please, fix it, or at least provide enough documentation on how to avoid this.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.wootric.androidsdk.objects.EndUser com.wootric.androidsdk.objects.WootricEvent.getEndUser()' on a null object reference
	at com.wootric.androidsdk.SurveyManager.onCreateEndUserSuccess(SurveyManager.java:251)
	at com.wootric.androidsdk.network.tasks.CreateEndUserTask.onSuccess(CreateEndUserTask.java:76)
	at com.wootric.androidsdk.network.tasks.WootricRemoteRequestTask.onPostExecute(WootricRemoteRequestTask.java:124)
	at com.wootric.androidsdk.network.tasks.WootricRemoteRequestTask.onPostExecute(WootricRemoteRequestTask.java:45)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
```

This is using 'com.wootric:wootric-sdk-android:2.21.1'

**Comment by diegoserranoa** [comment]
Hi @nordfalk 

Thanks for all the details and investigation regarding this. Sorry that you've had to deal with this. I created a ticket for this issue and we're going to start working on it. I'll let you know as soon as I have an update.

**Comment by nordfalk** [comment]
Dear @diegoserranoa , thanks for starting working on this. 
Are there any news, or a probable timeline?

We have implemented Wootric in our mobile apps (https://dinero.dk - its a bookkeeping app) but had to turn it completely off on Android because of this crash.

We need to be able to stop it from popping up on some critical subscreens on the app (i.a. when the user is taking a picture of a receipt, or sending an invoice via our app).

In iOS we can have Wootric to only show up when the user is at the front screen of the app, but in Android we are using fragments - and as Wootric ties itself to the Actitivy it can just popup anytime, also on very annoying occasions.

So we need either to be able to turn it off (invoke wootric.stop()), or to tie it to a fragment (not activity) so its isnt shown in critical sections of your app.

Looking forward to hear from you

Yours
Jacob Nordfalk

Androidudvikler på [Dinero](https://dinero.dk/om-os/holdet/#jacob-nordfalk)
Tlf. 26206512
Visma dinero ApS
Emil Christian Hansens Hus
Gærtorvet 1-5, 1799, København V

**Comment by diegoserranoa** [comment]
Hi @nordfalk, sorry for the lack of update. I've been trying to fix this but I still can't find a good solution for the stop() bug. This week I'm going to try and explore the possibility of being able to tie the survey to a Fragment. I have a lot on my plate right now so please bear with me 🙏 I'm really sorry this is taking so long...

**Comment by diegoserranoa** [comment]
Please check version 2.24.2 which contains the fix for this.

**Comment by nordfalk** [comment]
The fix works - I havent had any of the above crashes since I upgraded to 2.24.2, so I think you can close this issue :-)

**Comment by diegoserranoa** [comment]
@nordfalk thanks for letting me know. I will close this issue now
